app:
  baseUrl: http://backstage.127.0.0.1.nip.io
backend:
  baseUrl: http://backstage.127.0.0.1.nip.io
  listen:
    port: 7007
    host: 0.0.0.0
integrations:
  github:
  - host: github.com
    token: ${GITHUB_TOKEN} # Needed to access github for creating new app
    apps:
    - $include: /tmp/backstage/github-credentials.yaml