app:
  baseUrl: https://backstage.${BASE_DOMAIN}
backend:
  baseUrl: https://backstage.${BASE_DOMAIN}
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: https://backstage.${BASE_DOMAIN}
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
integrations:
  github:
  - host: github.com
    apps:
    - $include: /tmp/backstage/github-credentials.yaml
techdocs:
  generator:
    runIn: 'local'