app:
  title: DevOps Syndicate - Center
  baseUrl: http://localhost:3000
organization:
  name: DevOps Syndicate
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  cache:
    store: memory
integrations:
  github:
  - host: github.com
    token: ${GITHUB_TOKEN} # Needed to access github for creating new app
    apps:
    - $include: github-credentials.yaml
techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_AUTH_CLIENT_ID}
        clientSecret: ${GITHUB_AUTH_CLIENT_SECRET}
scaffolder:
  defaultAuthor:
    name: Backstage App Creator
    email: backstage@devops-syndicate.github.com
  defaultCommitMessage: "New app created"
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
  - allow: [Component, System, API, Resource, Location, Template]
  locations:
  - type: github-discovery
    target: https://github.com/devops-syndicate