app:
  title: DevOps Syndicate - Center
  baseUrl: http://localhost:3000
organization:
  name: DevOps Syndicate
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  cache:
    store: memory
integrations:
  github:
  - host: github.com
    apps:
    - $include: github-credentials.yaml
proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true
techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_AUTH_CLIENT_ID}
        clientSecret: ${GITHUB_AUTH_CLIENT_SECRET}
scaffolder:
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
  - allow: [Component, System, API, Resource, Location]
  locations:
  - type: file
    target: ../../examples/entities.yaml
  - type: file
    target: ../../examples/template/template.yaml
    rules:
      - allow: [Template]
  - type: file
    target: ../../examples/org.yaml
    rules:
    - allow: [User, Group]