apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: The backstage app for devops-syndicate
  annotations:
    github.com/project-slug: devops-syndicate/backstage
  tags:
  - nodejs
spec:
  type: service
  owner: admins
  lifecycle: production
